### ISSUE TITLE
Report processor failed: undefined method `empty?' for nil:NilClass

### ISSUE THREAD

**Issue by lvg** [fiddyspence/puppet-mconotify#1]
On command
"svcs.runonce(:forcerun=> true, :process_results => false)"
the reportprocessor exits with
"Report processor failed: undefined method `empty?' for nil:NilClass"

Transforming the part
":filter=>{"cf_class"=>[], "agent"=>["puppetd"], "identity"=>[thefilter], "fact"=>factfilter},"
in the preceding code to
":class_filter=>[], :agent_filter=>["puppetd"], :identity_filter=>[thefilter], :fact_fileter=>factfilter,"
the code runs as espected.

This is example is from the node part, the class part must have the same adjustment.

Used version of mcollective client is 2.2.3 (current stable version)

**Comment by fiddyspence** [comment]
Just taking a look at this now - sorry for the delay, missed the notification.

**Comment by fiddyspence** [comment]
Turns out it also needs a compound filter for mco 2 - updated and tested.
