### ISSUE TITLE
class filter does not accept subclasses

### ISSUE THREAD

**Issue by lvg** [fiddyspence/puppet-mconotify#2]
The class::subclass class gets split up in two classes (class and subclass). On the commandline (mco puppetd status -A puppetd -C "class::subclass") then command works as espected.

**Comment by fiddyspence** [comment]
Some of this is down to the way puppet deals with tagging - puppet splits class namespaces and tags with all of them, hence a class foo::bar will give you two tags - foo and foo::bar.  Try using a different delimiter, such as '--', or post more sample code.

**Comment by fiddyspence** [comment]
Looking at this some more, the only way to get round it is to have _another_ delimiter, so the mco tag would be:

'mconotify--class--foo..bar' which we then sub in the report processor /../::/

This is frankly insane, but I might have a crack at some sample code.

**Comment by fiddyspence** [comment]
Fixed
