### ISSUE TITLE
init.pp configures for puppet-enterprise while mconotify has allready a configuration

### ISSUE THREAD

**Issue by lvg** [fiddyspence/puppet-mconotify#3]
Hello,

we're using public domain puppet with a mcollective configured with it's own puppet module. With version 0.3.0 mconotify configures itself with mcollective. This cannot be disabled in the module and conflicts with the current installation.

Besides we're using foreman to configure our hosts. We can include modules on a host but can't provice class parameters. That results in a puppet-enterprise like installation of mconotify by default. We can work around this using our own class calling the mconotify class but maybe the mconotify class can be adjusted to support puppet-enterprise and public domain puppet?

Kind regards

**Comment by fiddyspence** [comment]
Pull requests always gratefully accepted.

**Comment by fiddyspence** [comment]
Closing for lack of interest
